<a href="https://colab.research.google.com/github/Imran20sw006/DS-A/blob/main/LAB4_20SW006.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Task 1
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [2]:
#Task 2
import numpy as np

X = np.arange(1, 26).reshape(5, 5)
odd_numbers = X[X % 2 != 0]

print("Original 5x5 ndarray:")
print(X)

print("\nOdd numbers using Boolean indexing:")
print(odd_numbers)


Original 5x5 ndarray:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Odd numbers using Boolean indexing:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [3]:
#Task 3
import numpy as np

X = np.arange(1, 5)[:, np.newaxis] * np.ones((4, 4))
print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [ ]:
#Task 4
import numpy as np

X = np.random.randint(0, 5001, size=(1000, 20))
print(X.shape)

ave_cols = np.mean(X, axis=0)
std_cols = np.std(X, axis=0)

print("Average of values in each column:", ave_cols)
print("Standard Deviation of values in each column:", std_cols)

ave_cols = np.mean(X, axis=0)
std_cols = np.std(X, axis=0)

print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

X_norm = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

ave_X_norm = np.mean(X_norm)
print("Average of all values in X_norm:", ave_X_norm)

ave_min_X_norm = np.mean(np.min(X_norm, axis=0))
print("Average of minimum value in each column of X_norm:", ave_min_X_norm)

ave_max_X_norm = np.mean(np.max(X_norm, axis=0))
print("Average of maximum value in each column of X_norm:", ave_max_X_norm)

permuted_indices = np.random.permutation(5)
row_indices = np.random.permutation(X_norm.shape[0])
X_norm_shuffled = X_norm[row_indices]


num_examples = X_norm.shape[0]
num_train = int(0.7 * num_examples)   # 70% for training
num_crossVal = int(0.15 * num_examples)   # 15% for cross-validation
num_test = num_examples - num_train - num_crossVal   # Remaining 15% for testing


X_train = X_norm_shuffled[:num_train]
X_crossVal = X_norm_shuffled[num_train:num_train + num_crossVal]
X_test = X_norm_shuffled[num_train + num_crossVal:]

print("Shape of X_train:", X_train.shape)
print("Shape of X_crossVal:", X_crossVal.shape)
print("Shape of X_test:", X_test.shape)
